apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "4"
data:
  DB_HOST: {{ pluck .Values.global.env .Values.database.host | first }}
